# Site settings
baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Okkur - Syna"
theme = "syna"
themesDir = "../.."
enableGitInfo = true
version = "0.13.0"
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]
paginate = 2

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

# Google Analytics tracking
googleAnalytics = ""

[params]
  name = "Okkur Labs"
  description = "Open Source Theme for your next project"

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"
    css = []
    js  = ["counter.js"]

  # Piwik tracking
  [params.analytics.piwik]
    url = "https://use.okkur.net"
    id = "13"
    domain = "syna-demo.okkur.io" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false

  [params.colors]
    white = "#fff"
    gray100 = "#f8f9fa" # light
    gray200 = "#e9ecef"
    gray300 = "#dee2e6"
    gray400 = "#ced4da"
    gray500 = "#adb5bd"
    gray600 = "#868e96" # secondary
    gray700 = "#495057"
    gray800 = "#343a40" # dark
    gray900 = "#212529"
    black = "#000"
    blue = "#00838F" # primary
    indigo = "#54008f"
    purple = "#8f0083"
    pink = "#c77fc1"
    red = "#dc1200" # danger
    orange = "#fd9742"
    yellow = "#fdf314" # warning
    green = "#008f54" # success
    teal = "#4cb087"
    cyan = "#00c9dc" # info

# main/prepend/postpend menus are displayed in nav fragment.
# footer/footer_social menus are displayed in footer fragment.
# copyright_footer menus are displayed in copyright fragment
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "/fragments"
  name = "Fragments"
  weight = 20

[[menu.main]]
  url = "/about"
  name = "About"
  weight = 30

[[menu.footer]]
  url = "https://github.com/okkur/syna/blob/master/docs/README.md"
  name = "Getting Started"
  weight = 10

[[menu.footer]]
  url = "https://about.okkur.io/"
  name = "About Okkur Labs"
  weight = 20

[[menu.footer_social]]
  weight = 30
  name = "github"
  url = "https://github.com/okkur/syna"
  pre = "fab fa-github fa-stack-2x"

[[menu.copyright_footer]]
  url = "/about"
  name = "About Us"
  weight = 10
